### ISSUE TITLE
RequireNamedArgsAttribute does not work when the method is called as extension method

### ISSUE THREAD

**Issue by kkkmail** [mykolav/require-named-args-fs#1]
Create an extension (note that the code below is not complete as it uses some more code to make it work, but I am sure that you will get the idea):
```
namespace Extensions
{
    public static class RatingTypeExt
    {
        [RequireNamedArgs]
        public static T Switch<T>(
            this RatingType ratingType,
            Func<T> onAdmitted,
            Func<T> onEAndS) =>
            ratingType == RatingType.Admitted ? onAdmitted() :
            ratingType == RatingType.EAndS ? onEAndS() :
            throw new InvalidDataException($"Invalid {nameof(RatingType)}: {ratingType ?? "<null>"}.");

        [RequireNamedArgs]
        public static void Switch(
            this RatingType workflowType,
            Action onAdmitted,
            Action onEAndS) =>
            Switch(
                ratingType: workflowType,
                onAdmitted: RatingType.ToFunc(onAdmitted),
                onEAndS: RatingType.ToFunc(onEAndS));
    }
}
```

"Observe" that the second `Switch` requires using `ratingType:` label (as it would be called in F# records). Without that label it won't compile.

Observe that the following method can be added (`throw` can be changed to some nice-behaving function without any compile errors):
```
        public static void IDontCareAboutNamedArguments(RatingType ratingType) =>
            ratingType.Switch(
                () => throw new InvalidDataException("onAdmitted"),
                () => throw new InvalidDataException("onEAndS"));
```
and it dos not care about `[RequireNamedArgs]` attached to any of the `Switch`-es.

**Comment by kkkmail** [comment]
The fix turned out to be trivial: method `RequireNamedArgsAnalyzer.filterSupported` should be updated to include `MethodKind.ReducedExtension`:
```
    member private this.filterSupported (methodSymbol: IMethodSymbol) = 
        match methodSymbol.MethodKind with
        // So far we only support analyzing one of the four kinds of methods listed below.
        |     MethodKind.Ordinary
            | MethodKind.Constructor
            | MethodKind.LocalFunction
            | MethodKind.ReducedExtension -> Some methodSymbol
        | _                            -> None
```
and that seems to do the trick.

I've created temporary nuget package:
https://www.nuget.org/packages/RequireNamedArguments 
and I will pull it out once you apply the fix (or fix it in some other way).

Thanks.

**Comment by mykolav** [comment]
Hi @kkkmail 
Sorry for a late replay.

Thank you very much for the detailed investigation!
I'll make time this weekend to merge the fix you suggest and publish the updated nuget package.

**Comment by mykolav** [comment]
It only took me forever ;)

But I finally applied your fix, @kkkmail Thank you!  
I'll upload an updated nuget package today.
