### ISSUE TITLE
Record types

### ISSUE THREAD

**Issue by cphillips83** [mykolav/require-named-args-fs#7]
```
[RequireNamedArgs]
public record UserCreate(string Login, string Email)
{
}
```

How do you apply required params to the ctor created by record types?

**Comment by mykolav** [comment]
Thank you for the question.

Finally, I got around to looking into it. 

The current version 0.0.6 of the NuGet package doesn't support applying `[RequireNamedArgs]` to a record's primary constructor. I'm uploading an updated package 0.0.7. 

Once [RequireNamedArgs 0.0.7](https://www.nuget.org/packages/RequireNamedArgs/0.0.7) is available for download from nuget.org, you can mark a record's primary constructor with `[RequireNamedArgs]` like in the following example:

```csharp

// Notice the `AttributeTargets.Class`,  `AttributeTargets.Struct` targets, 
// they tell the compiler, this attribute can be applied to `record` and `record struct`
[AttributeUsage(AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Class | AttributeTargets.Struct)]
class RequireNamedArgsAttribute : Attribute {}


[RequireNamedArgs]
record Character(string Name, int PowerLevel) {}

[RequireNamedArgs]
record struct CharacterStruct(string Name, int PowerLevel) {}

// Elsewhere in your code:
// if the primary constructor of `Character` or `CharacterStruct` is called with positional arguments,
// the analyzer will emit an error.
new Character(Name: "Goku", PowerLevel: 9001);
new CharacterStruct(Name: "Goku", PowerLevel: 9001);
```

Please note, in the code above the attribute only applies to the primary constructors of the records. If a record has additional constructors, you can mark them with this attribute individually in a normal way.
